# Generated by Django 5.2.7 on 2026-06-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_institute_landesstelle_landesstellefundingshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='landesstelle',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.institute'),
        ),
        migrations.DeleteModel(
            name='LandesstelleFundingShare',
        ),
    ]
