# Generated by Django 5.2.7 on 2026-06-20 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_landesstelle_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landesstelle',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
