# Generated by Django 5.2.7 on 2026-06-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_landesstelle_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
