# Generated by Django 5.2.7 on 2026-06-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_final_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='final_end_date',
        ),
    ]
