# Generated by Django 5.2.7 on 2026-06-21 08:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_final_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_own_chair',
            field=models.BooleanField(default=False, help_text='Markiert den eigenen Lehrstuhl. Overhead-Anteile dieses Instituts gelten als verfügbar.'),
        ),
        migrations.CreateModel(
            name='OverheadBudgetItemShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.institute')),
                ('overhead_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.overheadbudgetitem')),
            ],
            options={
                'unique_together': {('overhead_item', 'institute')},
            },
        ),
    ]
