# Generated by Django 5.2.7 on 2026-06-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_institute_is_own_chair_overheadbudgetitemshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_mode',
            field=models.CharField(choices=[('fixed_grant', 'Drittmittelprojekt (fixe Fördersumme)'), ('annual_pool', 'Jahresmittel/Studienmittel (jährlicher Topf)')], default='fixed_grant', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProjectAnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount_assigned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('project', 'year')},
            },
        ),
    ]
