# Generated by Django 5.2.7 on 2026-06-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_budget_mode_alter_project_budget_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_mode',
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='AnnualPoolBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount_assigned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('annual_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.annualpool')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('annual_pool', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='ProjectAnnualBudget',
        ),
    ]
