# Generated by Django 5.2.5 on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_projectmilestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAPFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund_number", models.CharField(max_length=100, unique=True, verbose_name="Fondsnummer")),
                ("label", models.CharField(blank=True, max_length=200, verbose_name="Bezeichnung")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "annual_pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_funds",
                        to="projects.annualpool",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_funds",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP-Fonds",
                "verbose_name_plural": "SAP-Fonds",
                "ordering": ["fund_number"],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("annual_pool__isnull", True), ("project__isnull", False))
                            | models.Q(("annual_pool__isnull", False), ("project__isnull", True))
                        ),
                        name="sap_fund_has_exactly_one_owner",
                    )
                ],
            },
        ),
    ]
