# Generated by Django 5.2.5 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_sapfund"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sapfund",
            name="sap_fund_has_exactly_one_owner",
        ),
        migrations.AddField(
            model_name="sapfund",
            name="is_universal",
            field=models.BooleanField(default=False, verbose_name="Universalprojekt"),
        ),
        migrations.AddConstraint(
            model_name="sapfund",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("annual_pool__isnull", True),
                        ("is_universal", False),
                        ("project__isnull", False),
                    )
                    | models.Q(
                        ("annual_pool__isnull", False),
                        ("is_universal", False),
                        ("project__isnull", True),
                    )
                    | models.Q(
                        ("annual_pool__isnull", True),
                        ("is_universal", True),
                        ("project__isnull", True),
                    )
                ),
                name="sap_fund_has_valid_owner",
                violation_error_message=(
                    "Ein SAP-Fonds muss einem Projekt oder Annual Pool zugeordnet "
                    "oder als Universalprojekt markiert sein."
                ),
            ),
        ),
    ]
