# Generated by Django 6.0.3 on 2026-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_sapfund_is_universal"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="no_overhead",
            field=models.BooleanField(default=False, verbose_name="Kein Overhead"),
        ),
    ]
