# Generated by Django 6.0.3 on 2026-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_sapfund_treat_negative_actuals_as_funding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffbudgetitemeligibility",
            name="eligible_employment",
            field=models.CharField(
                choices=[
                    ("professor", "Professoren"),
                    ("student", "Studentische Hilfskraft"),
                    ("undergrad", "Nicht-Wissenschaftliche Mitarbeiter"),
                    ("researcher", "Wissenschaftliche Mitarbeiter"),
                ],
                max_length=50,
            ),
        ),
    ]
