# Generated by Django 6.0.3 on 2026-10-02 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_professor_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bezeichnung"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Beginn")),
                ("end_date", models.DateField(verbose_name="Ende")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_periods",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Berichtszeitraum",
                "verbose_name_plural": "Berichtszeiträume",
                "ordering": ["start_date"],
            },
        ),
    ]
