"""
Django settings for groupplanning project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(name, default):
    return int(os.getenv(name, str(default)))


def env_float(name, default):
    return float(os.getenv(name, str(default)))


def env_path(name, default):
    raw_value = os.getenv(name)
    if raw_value is None:
        raw_value = str(default)
    expanded = os.path.expanduser(os.path.expandvars(str(raw_value)))
    return Path(expanded)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-y9mg=*c&!q%&+p$s9i3*4aw^_%s7h6d70s5ur_(u3o-*23199(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', ['localhost', '127.0.0.1', '[::1]'])
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS', [])


# Application definition

INSTALLED_APPS = [
    'controlling.apps.ControllingConfig',
    'projects.apps.ProjectsConfig',
    'staffing.apps.StaffingConfig',
    'sap_integration.apps.SAPIntegrationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'django_crontab',
]

if DEBUG:
    INSTALLED_APPS += [
        'django_browser_reload',
        'django_model_info.apps.DjangoModelInfoConfig',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'groupplanning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [''],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'controlling.context_processors.config_settings',
                'sap_integration.context_processors.sap_feature',
            ],
        },
    },
]

WSGI_APPLICATION = 'groupplanning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env_path('DJANGO_DB_NAME', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-DE'
USE_THOUSAND_SEPARATOR = True

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Deployment-specific static files (e.g. a custom BRAND_LOGO) that
# shouldn't live in the tracked app code. Gitignored; each deployment
# drops its own files in here.
STATICFILES_DIRS = [BASE_DIR / 'branding']

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if env_bool('DJANGO_SECURE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'main'
LOGOUT_REDIRECT_URL = 'login'

# Email Configuration
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# SQLite database backups (optional)
DB_BACKUP_ENABLED = env_bool('DB_BACKUP_ENABLED', False)
DB_BACKUP_DIR = env_path('DB_BACKUP_DIR', BASE_DIR / 'backups')
DB_BACKUP_CRON = os.getenv('DB_BACKUP_CRON', '0 2 * * *').strip()
DB_BACKUP_KEEP_DAILY = env_int('DB_BACKUP_KEEP_DAILY', 7)
DB_BACKUP_KEEP_MONTHLY = env_int('DB_BACKUP_KEEP_MONTHLY', 12)
DB_BACKUP_KEEP_YEARLY = env_int('DB_BACKUP_KEEP_YEARLY', 1)
NEXTCLOUD_BACKUP_SHARE_URL = os.getenv('NEXTCLOUD_BACKUP_SHARE_URL', '')
NEXTCLOUD_BACKUP_SHARE_PASSWORD = os.getenv('NEXTCLOUD_BACKUP_SHARE_PASSWORD', '')
NEXTCLOUD_BACKUP_TIMEOUT = env_int('NEXTCLOUD_BACKUP_TIMEOUT', 60)

# Controlling Configuration

# Whether overhead budgets are split between the own chair ("Lehrstuhl")
# and other institutes. Some deployments only ever have a single
# institute, so the split (and its UI) can be disabled entirely.
OVERHEAD_SPLIT_ENABLED = env_bool('OVERHEAD_SPLIT_ENABLED', True)

# Whether the Landesstellen and Annual Pools funding-source features are
# used. Some deployments don't need them, so their navigation, UI
# sections, and related warnings can be disabled entirely.
LANDESSTELLEN_ENABLED = env_bool('LANDESSTELLEN_ENABLED', True)
ANNUAL_POOLS_ENABLED = env_bool('ANNUAL_POOLS_ENABLED', True)

# Static-file path (relative to a static dir) of the logo shown in the
# navbar. Deployments can swap in their own branding by dropping a file
# under static/ and pointing this at it. Set to an empty string to hide
# the logo entirely.
BRAND_LOGO = os.getenv('BRAND_LOGO', 'controlling/img/Symbol_White.svg')

# Optional SAP WebGUI integration. Credentials are only read by the sync command.
SAP_ENABLED = env_bool('SAP_ENABLED', False)
SAP_URL = os.getenv('SAP_URL', '')
SAP_USER = os.getenv('SAP_USER', '')
SAP_PASSWORD = os.getenv('SAP_PASSWORD', '')
SAP_FINANZSTELLE = os.getenv('SAP_FINANZSTELLE', '')
SAP_DATA_DIR = env_path('SAP_DATA_DIR', BASE_DIR / 'sap_data')
SAP_BROWSER = os.getenv('SAP_BROWSER', 'firefox')
SAP_BROWSER_BINARY = os.getenv('SAP_BROWSER_BINARY', '')
SAP_HEADLESS = env_bool('SAP_HEADLESS', True)
SAP_TIMEOUT = env_int('SAP_TIMEOUT', 60)
SAP_ACTION_DELAY = env_float('SAP_ACTION_DELAY', 1.0)
SAP_SYNC_CRON = os.getenv('SAP_SYNC_CRON', '0 5 * * *').strip()
SAP_BACKEND = os.getenv(
    'SAP_BACKEND',
    'sap_integration.backends.wuerzburg.WuerzburgWebGUIBackend',
)
# Upload of SAP Grants Management project exports (GM_E_4GBA) and their
# reconciliation with the planning. Independent of the WebGUI download above.
SAP_GM_IMPORT_ENABLED = env_bool('SAP_GM_IMPORT_ENABLED', False)

# Cron Jobs Configuration
# https://github.com/hartwork/django-crontab
CRONJOBS = [
    ('0 8 * * *', 'django.core.management.call_command', ['send_notifications'], {}, '>> /tmp/cron_notifications.log 2>&1'),
]

if DB_BACKUP_ENABLED:
    CRONJOBS.append(
        (
            DB_BACKUP_CRON,
            'django.core.management.call_command',
            ['backup_database'],
            {},
            '>> /tmp/cron_backup.log 2>&1',
        )
    )

if SAP_ENABLED:
    CRONJOBS.append(
        (
            SAP_SYNC_CRON,
            'django.core.management.call_command',
            ['sync_sap'],
            {},
            '>> /tmp/cron_sap.log 2>&1',
        )
    )
