# Generated by Django 6.0.3 on 2026-09-30 12:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0013_project_no_overhead"),
        ("staffing", "0008_stafffundingallocation_sap_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SAPImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="Datei")),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Importiert am"
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Buchungszeilen"
                    ),
                ),
                ("first_booking", models.DateField(blank=True, null=True)),
                ("last_booking", models.DateField(blank=True, null=True)),
                ("cost_types", models.JSONField(default=dict)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_imports",
                        to="projects.sapfund",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP-Import",
                "verbose_name_plural": "SAP-Importe",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="SAPPersonMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_key", models.CharField(max_length=200, unique=True)),
                (
                    "sap_name",
                    models.CharField(max_length=200, verbose_name="Name in SAP"),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sap_name_mappings",
                        to="staffing.staffmember",
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP-Namenszuordnung",
                "verbose_name_plural": "SAP-Namenszuordnungen",
                "ordering": ["sap_name"],
            },
        ),
        migrations.CreateModel(
            name="SAPCostTypeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_type", models.CharField(max_length=50, verbose_name="E/A-Art")),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_type_mappings",
                        to="projects.sapfund",
                    ),
                ),
                (
                    "other_budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.otherbudgetitem",
                        verbose_name="Sachmittelbudget",
                    ),
                ),
                (
                    "staff_budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.staffbudgetitem",
                        verbose_name="Personalbudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP-E/A-Art-Zuordnung",
                "verbose_name_plural": "SAP-E/A-Art-Zuordnungen",
                "ordering": ["fund", "cost_type"],
                "unique_together": {("fund", "cost_type")},
            },
        ),
        migrations.CreateModel(
            name="SAPIgnoredPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=50, verbose_name="Referenzbelegnummer"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Notiz"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_positions",
                        to="projects.sapfund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignorierte SAP-Position",
                "verbose_name_plural": "Ignorierte SAP-Positionen",
                "unique_together": {("fund", "reference")},
            },
        ),
        migrations.CreateModel(
            name="SAPPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=50, verbose_name="Referenzbelegnummer"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("staff", "Personal"),
                            ("travel", "Reise"),
                            ("other", "Sachmittel"),
                            ("income", "Einnahme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cost_type", models.CharField(max_length=50, verbose_name="E/A-Art")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Bezeichnung"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Text")),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Person"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vertragsart"
                    ),
                ),
                ("contract_periods", models.JSONField(default=list)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weekly_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("first_date", models.DateField(blank=True, null=True)),
                ("last_date", models.DateField(blank=True, null=True)),
                (
                    "actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ist",
                    ),
                ),
                (
                    "commitment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Obligo",
                    ),
                ),
                ("monthly_actuals", models.JSONField(default=dict)),
                ("bookings", models.JSONField(default=list)),
                (
                    "sap_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="sap_integration.sapimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP-Position",
                "verbose_name_plural": "SAP-Positionen",
                "ordering": ["kind", "person_name", "first_date", "reference"],
                "unique_together": {("sap_import", "reference")},
            },
        ),
    ]
