# Generated by Django 5.2.7 on 2025-10-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("student", "Studentische Hilfskraft"),
                            ("undergrad", "Nicht-Wissenschaftliche Mitarbeiter"),
                            ("researcher", "Wissenschaftliche Mitarbeiter"),
                        ],
                        default="researcher",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_hire", "Einstellung"),
                            ("active", "Aktiv"),
                            ("alumni", "Alumni"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentSalaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "employment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staffing.employment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "budget_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.staffbudgetitem",
                    ),
                ),
                (
                    "employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staffing.employment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employment",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffing.staffmember"
            ),
        ),
    ]
