# Generated by Django 5.2.7 on 2026-06-20 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_institute_landesstelle_landesstellefundingshare'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFundingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.staffbudgetitem')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.employment')),
                ('landesstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.landesstelle')),
            ],
        ),
    ]
