# Generated by Django 5.2.7 on 2026-06-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_annualpool_remove_project_budget_mode_and_more'),
        ('staffing', '0002_stafffundingallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffundingallocation',
            name='annual_pool_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.annualpoolbudget'),
        ),
    ]
