# Generated by Django 5.2.7 on 2026-06-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_stafffundingallocation_annual_pool_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
    ]
