# Generated by Django 5.2.7 on 2026-07-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_delete_staffassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
