# Generated by Django 5.2.7 on 2026-07-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0005_staffmember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text='Person hat Leitungsfunktion (z.B. Professor)'),
        ),
    ]
