# Generated by Django 6.0.3 on 2026-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0007_remove_stray_employmentsalaries_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafffundingallocation",
            name="sap_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Referenzbelegnummer der SAP-Mittelreservierung, z.B. 4000123",
                max_length=50,
                verbose_name="SAP-Referenz",
            ),
        ),
    ]
