# Generated by Django 5.2.8 on 2026-10-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0008_stafffundingallocation_sap_reference"),
        ("staffing", "0010_employmentsalaries_is_exact_amount"),
    ]

    operations = []
