# Generated by Django 6.0.3 on 2026-10-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0011_merge_20261001_1140"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Entgeltgruppe",
                "verbose_name_plural": "Entgeltgruppen",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employment",
            name="salary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="staffing.salarycategory",
                verbose_name="Entgeltgruppe",
            ),
        ),
    ]
