# Generated by Django 6.0.3 on 2026-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0012_salarycategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="level_start_date",
            field=models.DateField(
                blank=True,
                help_text="Ab wann die Stufe bei Beginn gilt; daraus folgen die weiteren Stufenaufstiege.",
                null=True,
                verbose_name="Stufenbeginn (fiktiv)",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="start_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Stufe 1"),
                    (2, "Stufe 2"),
                    (3, "Stufe 3"),
                    (4, "Stufe 4"),
                    (5, "Stufe 5"),
                    (6, "Stufe 6"),
                ],
                null=True,
                verbose_name="Stufe bei Beginn",
            ),
        ),
    ]
