# Generated by Django 6.0.3 on 2026-10-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0013_employment_tvl_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("valid_from", models.DateField(verbose_name="Gültig ab")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Leer lassen, solange die Tabelle gilt.",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entgelttabelle",
                "verbose_name_plural": "Entgelttabellen",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="SalaryTableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Stufe 1"),
                            (2, "Stufe 2"),
                            (3, "Stufe 3"),
                            (4, "Stufe 4"),
                            (5, "Stufe 5"),
                            (6, "Stufe 6"),
                        ],
                        verbose_name="Stufe",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Brutto inkl. Arbeitgeberanteile, bei Vollzeit (100 %).",
                        max_digits=10,
                        verbose_name="Monatliche Personalkosten",
                    ),
                ),
                (
                    "salary_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staffing.salarycategory",
                        verbose_name="Entgeltgruppe",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="staffing.salarytable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabellenwert",
                "verbose_name_plural": "Tabellenwerte",
                "ordering": ["salary_category__name", "level"],
                "unique_together": {("table", "salary_category", "level")},
            },
        ),
    ]
