# Generated by Django 6.0.3 on 2026-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0014_salarytable"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Geplant"),
                    ("contract", "Vertrag"),
                    ("rebook", "Umbuchung"),
                ],
                default="contract",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
