# Generated by Django 6.0.3 on 2026-10-02 04:26

from django.db import migrations, models


def set_special_payment_rates(apps, schema_editor):
    from staffing.tvl import special_payment_rate_for

    SalaryCategory = apps.get_model("staffing", "SalaryCategory")
    for category in SalaryCategory.objects.filter(special_payment_rate__isnull=True):
        category.special_payment_rate = special_payment_rate_for(category.name)
        category.save(update_fields=["special_payment_rate"])


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0015_employment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycategory",
            name="special_payment_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prozentsatz nach § 20 Abs. 2 TV-L, z. B. 46,47 für E 12–13.",
                max_digits=5,
                null=True,
                verbose_name="Jahressonderzahlung (%)",
            ),
        ),
        migrations.AddField(
            model_name="salarytableentry",
            name="gross",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Brutto ohne Arbeitgeberanteile, bei Vollzeit (100 %); Grundlage der Jahressonderzahlung.",
                max_digits=10,
                null=True,
                verbose_name="Tabellenentgelt",
            ),
        ),
        migrations.RunPython(set_special_payment_rates, migrations.RunPython.noop),
    ]
