# Generated by Django 6.0.3 on 2026-10-02 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_sapfund_treat_negative_actuals_as_funding"),
        ("staffing", "0016_special_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="stafffundingallocation",
            name="is_rebooking",
            field=models.BooleanField(
                default=False,
                help_text="Durch eine abgeschlossene Umbuchung entstanden.",
                verbose_name="Umgebucht",
            ),
        ),
        migrations.CreateModel(
            name="Rebooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Umfang (%)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ab")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leer lassen für das Ende der Zuordnung.",
                        null=True,
                        verbose_name="Bis",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebookings",
                        to="staffing.stafffundingallocation",
                        verbose_name="Zuordnung",
                    ),
                ),
                (
                    "budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.staffbudgetitem",
                        verbose_name="Nach (Personalbudget)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umbuchung",
                "verbose_name_plural": "Umbuchungen",
                "ordering": ["start_date", "pk"],
            },
        ),
    ]
