# Generated by Django 6.0.3 on 2026-10-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0017_rebooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="category",
            field=models.CharField(
                choices=[
                    ("professor", "Professoren"),
                    ("student", "Studentische Hilfskraft"),
                    ("undergrad", "Nicht-Wissenschaftliche Mitarbeiter"),
                    ("researcher", "Wissenschaftliche Mitarbeiter"),
                ],
                default="researcher",
                max_length=50,
            ),
        ),
    ]
