# Generated by Django 6.0.3 on 2026-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffing", "0018_professor_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="statutory_health_insurance",
            field=models.BooleanField(
                default=True,
                help_text="Aus, wenn keine Arbeitgeberanteile zur Kranken- und Pflegeversicherung anfallen (z. B. privat versichert).",
                verbose_name="Gesetzlich krankenversichert",
            ),
        ),
    ]
