# Generated by Django 5.2.7 on 2026-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contract_expiry', 'Vertrag läuft aus'), ('milestone_due', 'Meilenstein fällig')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('related_object_type', models.CharField(max_length=50)),
                ('related_object_id', models.IntegerField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_date'],
                'unique_together': {('notification_type', 'recipient_email', 'related_object_type', 'related_object_id')},
            },
        ),
    ]
