# Generated by Django 6.0.3 on 2026-10-01 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("comment", models.TextField(verbose_name="Begründung")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ignoriert am"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignorierte Warnung",
                "verbose_name_plural": "Ignorierte Warnungen",
                "ordering": ["-created_at"],
            },
        ),
    ]
